name: GithubPages

on:
  push:
    branches:
      - main
    paths:
      - 'examples/**'
      - 'index.html'
      - "assets/**"
      - "js/**"
      - "css/**"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          cname: threejs.gh.yycc.dev